- README.md
- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/MainActivity.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inboard/InBoardAdFactoryScrollViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inboard/InBoardWebViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadWebViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/utils/BaseFragment.java
- TeadsSDKDemo/app/src/main/res/layout/activity_main.xml
- TeadsSDKDemo/app/src/main/res/layout/navigation_drawer.xml
- TeadsSDKDemo/app/src/main/res/values/strings.xml
- TeadsSDKDemo/app/src/main/res/values/styles.xml
> Merge develop for version 1.2.4

- README.md
- TeadsSDKDemo/app/build.gradle
> Update Demo app with SDK version 1.4.3

- README.md
- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/app/build.gradle
- Implement isVisible(int offset) method in TeadsVideoView
> Update to version 1.5.8

- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/build.gradle
- TeadsSDKDemo/gradle/wrapper/gradle-wrapper.properties
update android gradle tools to 1.3.1 and gradle distribution version to 2.6
> Update gradle versions

- TeadsSDKDemo/.gitignore
- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/signing.properties
Release flavor created is "releaseSigned"
> Add signing config with empty signing.properties

- README.md
- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to v1.5.10

- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/app/build.gradle
Update the app Teads SDK version to 1.5.12 (should have been in last commit)
> Update SDK Version

- README.md
- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/app/build.gradle
- fix a bug related to tracking user agent
> Teads SDK version 1.6.6

- README.md
- TeadsSDKDemo/app/app.iml
- TeadsSDKDemo/app/build.gradle
v1.6.7:
- Fix two issues related to db and progressBar
> Update Teads SDK to v1.6.7

- CHANGELOG.md
- README.md
- TeadsSDKDemo/.idea/encodings.xml
- TeadsSDKDemo/.idea/gradle.xml
- TeadsSDKDemo/app/build.gradle
Changelog:
- RecyclerView fix
- minor bug fix and improvements
> Teads SDK v2.0.24

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Teads SDK to 2.0.25

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- change ExoPlayer dependency to prevent conflict
- minor fix
> Update Teads SDK to v2.0.27

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to v2.0.28

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to v2.0.29

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- improve memory management
- fix issues when cleaning `TeadsVideo` with null views
>  Teads SDK to 2.0.32

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/InFlowFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadListViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadRecyclerViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadScrollViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadWebViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopListViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopRecyclerViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopScrollViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopWebViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/videoview/AdvancedVideoViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/videoview/ScrollViewVideoViewFragment.java
- TeadsSDKDemo/build.gradle
- TeadsSDKDemo/gradle/wrapper/gradle-wrapper.properties
v2.1.0:
- internal dependency change
- use OkHttp 3.2.0
> Update Teads SDK to v2.1.0

- CHANGELOG.md
- README.md
- TeadsSDKDemo/.idea/misc.xml
- TeadsSDKDemo/app/build.gradle
- fix video not resuming sometimes
> Update Teads SDK to 2.1.3

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- Fix memory leaks
- Minor bug fix
> Update Teads SDK to 2.1.4

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
Teads SDK 2.2.7
- webview reuse enchancement
- minor improvements
> Update Teads SDK to 2.2.7

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- Teads SDK 2.2.8 include minor bug fixes
> Update Teads SDK to 2.2.8

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to 2.2.10

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- funnel improvement
- bug fix
> Update Teads SDK to v2.2.11

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- test.sh
- improve tracking reliability
- bug fix
> Update Teads SDK to 2.2.12

- CHANGELOG.md
- README.md
- TeadsSDKDemo/.idea/gradle.xml
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/build.gradle
- TeadsSDKDemo/gradle/wrapper/gradle-wrapper.properties
- test.sh
- Add the possibility to disable application visibility receiver in
TeadsConfiguration
- leak memory fix on webview container
- bug fix
> Update Teads SDK to 2.2.14

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- fix an issue with the complete tracking
> Update SDK to 2.2.15

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/MainActivity.java
- support vpaid creatives
- remove TeadsVideo object
- bug fix
> Update Teads sdk version to 2.3.6

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- add behavior on equalizer click 
> Update Teads SDK to 2.3.7

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- minor bug fix and improvement
> Update Teads SDK to 2.3.10

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK version to 2.3.11

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- remove  `android.permission.ACCESS_WIFI_STATE`
> Update Teads SDK to 2.3.12

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- update play services version to 10.2.0
- update support android version to 25.2
- update compile android SDK version to 25
> Update Teads SDK to v2.3.16

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to 2.3.17

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to 2.4.1

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- minor improvement and bug fix
> Update Teads SDK version code to 2.4.2

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/adview/AdvancedAdViewFragment.java
> Update Teads SDK to 2.4.6

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/adview/AdvancedAdViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/adview/ScrollViewAdViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadListViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadRecyclerViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadScrollViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadWebViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopListViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopRecyclerViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopScrollViewFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inreadTop/InReadTopWebViewFragment.java
- No need to pass Activity at TeadsAd object anymore, a context is enough 
- bug fix and memory improvement
> Update Teads SDK to 2.4.9

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- Remove WRITE_EXTERNAL_STORAGE permission
- Support x-javascript MIME type for VPAID creative
- bug fix
> Update Teads SDK version to 2.4.11

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to 2.5.6

- TeadsSDKDemo/webviewhelper/src/main/assets/bootstrap.js
- TeadsSDKDemo/webviewhelper/src/main/java/tv/teads/webviewhelper/TeadsWebViewSynchronizer.java
- TeadsSDKDemo/webviewhelper/src/main/java/tv/teads/webviewhelper/WebViewHelper.java
https://jira.teads.net/browse/FOR-2166
> Open slot when needed and remove animation in bootstrap

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
> Update Teads SDK to 2.5.10

- CHANGELOG.md
- README.md
- TeadsSDKDemo/TeadsSDKDemo.iml
- TeadsSDKDemo/app/build.gradle
- Bug fixes on custom integration
> Update Teads SDK to 2.5.12

- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/example/ExampleFragment.java
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/AdMobBannerFragment.java
- TeadsSDKDemo/app/src/main/res/layout/fragment_admob_banner.xml
- TeadsSDKDemo/app/src/main/res/layout/fragment_example.xml
- TeadsSDKDemo/app/src/main/res/values/strings.xml
Full documentation: https://mobile.teads.tv/sdk/documentation/android/mediation/admob
> Add AdMob Mediation sample

- CHANGELOG.md
- README.md
- TeadsSDKDemo/build.gradle
- TeadsSDKDemo/webviewhelper/src/main/java/tv/teads/webviewhelper/WebViewHelper.java
- TeadsSDKDemo/webviewhelper/webviewhelper.iml
- fix `CustomAdView` & `InReadAdView` state restoration
- fix `onAdVolumeChange` not fired on `TeadsListener`
> Update Teads SDK to v4.1.1

- CHANGELOG.md
- README.md
- TeadsSDKDemo/build.gradle
- Disable SDK for API under 19
- Fix ad view player size
- Improve performances
> Update SDK to 4.1.2

- CHANGELOG.md
- README.md
- TeadsSDKDemo/app/build.gradle
- TeadsSDKDemo/app/src/main/AndroidManifest.xml
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/MainActivity.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/MainFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/adapter/AdMobRecyclerViewAdapter.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/adapter/MoPubRecyclerViewAdapter.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/adapter/SmartRecyclerViewAdapter.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/admob/AdMobGridRecyclerViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/admob/AdMobRecyclerViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/admob/AdMobScrollViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/admob/AdMobWebViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/mopub/MopubScrollViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/mopub/MopubWebViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/smart/SmartScrollViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/smart/SmartWebViewFragment.kt
- TeadsSDKDemo/build.gradle
- TeadsSDKDemo/gradle.properties
- Update Teads SDK to 4.9.0
- Fix leak in the sample project
- Update dependencies
> Update SDK to 4.9.0

- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/inread/InReadScrollViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/adapter/AppLovinRecyclerViewAdapter.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/applovin/AppLovinRecyclerViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/applovin/AppLovinScrollViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/mediation/applovin/AppLovinWebViewFragment.kt
- TeadsSDKDemo/app/src/main/res/layout/fragment_inread_view_scrollview.xml
> Fix error regarding missing view; add correct config to get ad unit from applovin

- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/MainFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/data/PidStore.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/infeed/InFeedScrollViewFragment.kt
- TeadsSDKDemo/app/src/main/java/tv/teads/teadssdkdemo/format/infeed/adapter/InFeedRecyclerViewAdapter.kt
- TeadsSDKDemo/app/src/main/res/layout/fragment_infeed_view_scrollview.xml
- Add as well fake gdpr str in order to be filled when using native pid
> Add scroll view implementation for inFeed
